pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'ntrangng/hermosa-menu-service'
        DOCKER_HUB_CREDS = 'docker-hub-creds'
        SONAR_TOKEN_ID = 'sonar-token'
        KUBECONFIG_CRED = 'kubeconfig-aws'
    }

    stages {
        stage('Stage 1: Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Stage 2: SonarQube Quality Scan') {
            steps {
                dir('Microservices') {
                    script {
                        def scannerHome = tool 'sonar-scanner'
                        withSonarQubeEnv('SonarQube') {
                            sh "${scannerHome}/bin/sonar-scanner -Dsonar.projectKey=hermosa-menu-service -Dsonar.sources=src/"
                        }
                    }
                }
            }
        }

        stage('Stage 3: Build & Security Scan (Trivy)') {
            steps {
                dir('Microservices') {
                    sh "docker build -t ${DOCKER_IMAGE}:latest -t ${DOCKER_IMAGE}:${env.BUILD_ID} ."
                   
                    sh "docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy image --severity HIGH,CRITICAL ${DOCKER_IMAGE}:latest"
                }
            }
        }

        stage('Stage 4: Push to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: "${DOCKER_HUB_CREDS}", passwordVariable: 'DOCKER_HUB_PASSWORD', usernameVariable: 'DOCKER_HUB_USERNAME')]) {
                    sh "echo \$DOCKER_HUB_PASSWORD | docker login -u \$DOCKER_HUB_USERNAME --password-stdin"
                    sh "docker push ${DOCKER_IMAGE}:latest"
                    sh "docker push ${DOCKER_IMAGE}:${env.BUILD_ID}"
                }
            }
        }

        stage('Stage 5: Deploy to Kubernetes') {
            steps {
                dir('Microservices') {
                    withCredentials([file(credentialsId: "${KUBECONFIG_CRED}", variable: 'KUBECONFIG')]) {
                        sh "kubectl apply -f k8s/deployment.yaml --validate=false"
                        sh "kubectl apply -f k8s/service.yaml --validate=false"
                    }
                }
            }
        }
    }

    post {
        always {
            echo "Pipeline hoàn tất. Kiểm tra kết quả trên Dashboard!"
        }
    }
}