pipeline {
    agent any

    environment {
        DOCKER_HUB_CREDENTIALS = 'docker-hub-trang' 
        SONAR_PROJECT_KEY = 'hermosa-menu-service'
        IMAGE_NAME = 'ntrangng/hermosa-menu-service'
    }

    stages {
        stage('Stage 1: Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Stage 2: SonarQube Quality Scan') {
            steps {
                dir('Microservices') {
                    script {
                        withSonarQubeEnv('SonarQube') {
                            sh """
                            docker run --rm --network host \
                                -e SONAR_HOST_URL=\$SONAR_HOST_URL \
                                -e SONAR_TOKEN=\$SONAR_AUTH_TOKEN \
                                -v \$(pwd):/usr/src \
                                sonarsource/sonar-scanner-cli \
                                -Dsonar.projectKey=${SONAR_PROJECT_KEY} \
                                -Dsonar.sources=src/
                            """
                        }
                    }
                }
            }
        }

        stage('Stage 3: Build & Security Scan (Trivy)') {
            steps {
                dir('Microservices') {
                    sh "docker build -t ${env.IMAGE_NAME}:latest -t ${env.IMAGE_NAME}:${env.BUILD_NUMBER} ."
                    sh "docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy image --severity HIGH,CRITICAL ${env.IMAGE_NAME}:latest"
                }
            }
        }

        stage('Stage 4: Push to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: "${env.DOCKER_HUB_CREDENTIALS}", passwordVariable: 'PASS', usernameVariable: 'USER')]) {
                    sh "echo ${PASS} | docker login -u ${USER} --password-stdin"
                    sh "docker push ${env.IMAGE_NAME}:latest"
                    sh "docker push ${env.IMAGE_NAME}:${env.BUILD_NUMBER}"
                }
            }
        }

        stage('Stage 5: Deploy to Kubernetes') {
            steps {
                dir('Microservices') {
                    sh "kubectl apply -f k8s/deployment.yaml --validate=false --insecure-skip-tls-verify=true"
                    sh "kubectl apply -f k8s/service.yaml --validate=false --insecure-skip-tls-verify=true"
                }
            }
        }
    }

    post {
        always {
            echo "Pipeline hoan tat. Kiem tra ket qua tren Dashboard!"
        }
    }
}